@startuml

class SineSignal {
+SineSignal(voltageOffset: double, timeOffset: Time, minVoltage: double, maxVoltage: double, period: Time)
+getVoltage(t: Time): double
}

class SawtoothSignal {
+SawtoothSignal(voltageOffset: double, timeOffset: Time, minVoltage: double, maxVoltage: double, period: Time)
+getVoltage(t: Time): double
}

abstract class PeriodicSignal {
-minValue: double
-maxValue: double
-period: Time

+PeriodicSignal(voltageOffset: double, timeOffset: Time, minVoltage: double, maxVoltage: double, period: Time)
+{abstract} getVoltageAtTime(t: Time): double
#getMinVoltage(): double
#getMaxVoltage(): double
#getPeriod(): Time
}

class ConstantSignal {
+ConstantSignal(voltageOffset: double, timeOffset: Time)
+getVoltage(t: Time): double
}

abstract class Signal {
-voltageOffset: double
-timeOffset: Time

+Signal(valueOffset: double, timeOffset: Time)
+{abstract} getVoltageAtTime(t: Time): double
#getVoltageOffset(): double
#getTimeOffset(): Time
}

PeriodicSignal <|-- SineSignal
PeriodicSignal <|-- SawtoothSignal

Signal <|-- ConstantSignal
Signal <|-- PeriodicSignal
@enduml
